services:
  - type: web
    name: employee-management-system
    env: java
    plan: free
    branch: main
    buildCommand: "./mvnw clean install"
    startCommand: "java -jar target/employee-management-system-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: PORT
        value: 8080
